Useful NumPy Functions

1. random
   - generates random floating-point numbers from[0.0, 1.0), 0.0 is included but 1.0 is not

In [2]:
import numpy as np
np.random.random(size=2)

array([0.12701826, 0.06640744])

In [3]:
np.random.normal(size=2)

array([ 0.05545746, -0.24961843])

In [4]:
np.random.rand(2, 4)

# generates a 2x4 array of random numbers from [0.0, 1.0)
# 0.0 (inclusive) and 1.0 (exclusive).

array([[0.657651  , 0.07213738, 0.64053743, 0.22539143],
       [0.30753653, 0.88179908, 0.16374817, 0.0722049 ]])

2. arange 
   - creates an array of evenly spaced values within a specified range
   - cakes up to three arguments: start, stop, and step
   - generated array:
     -  includes the start value 
     -  excludes the stop value
     -  step determines the spacing between consecutive values