Useful NumPy Functions

1. random
   - generates random floating-point numbers from[0.0, 1.0), 0.0 is included but 1.0 is not

In [2]:
import numpy as np
np.random.random(size=2)

array([0.12701826, 0.06640744])

In [3]:
np.random.normal(size=2)

array([ 0.05545746, -0.24961843])

In [4]:
np.random.rand(2, 4)

# generates a 2x4 array of random numbers from [0.0, 1.0)
# 0.0 (inclusive) and 1.0 (exclusive).

array([[0.657651  , 0.07213738, 0.64053743, 0.22539143],
       [0.30753653, 0.88179908, 0.16374817, 0.0722049 ]])

2. arange 
   - creates an array of evenly spaced values within a specified range
   - cakes up to three arguments: start, stop, and step
   - generated array:
     -  includes the start value 
     -  excludes the stop value
     -  step determines the spacing between consecutive values

In [5]:
np.arange(10)

#  generates an array of values from 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(5, 10)

# generates an array of values starting from 5 and ending at 9

array([5, 6, 7, 8, 9])

In [7]:
np.arange(0, 1, .1)

# generates an array of values starting from 0 and ending at 1, with a step size of 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

3. reshape 
   - change the shape of an array without changing its data
   - rearrange the elements of an array into a new shape while keeping the same data

In [8]:
np.arange(10).reshape(2, 5)

# creates an array of values from 0 to 9 and then reshapes it into a 2x5 array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
np.arange(10).reshape(5, 2)

# creates an array of values from 0 to 9 and then reshapes it into a 5x2 array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

4. linspace 
   - generate array of evenly spaced values within specified range
   - similar to arange function
       - instead of specifying step size, specify # of points wanted in generated array
   - returns an array of num values evenly spaced between start and stop, inclusive

In [10]:
np.linspace(0, 1, 5)

# generates an array of 5 evenly spaced values from 0 to 1, inclusive

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
np.linspace(0, 1, 20, False)

# since False the generated array will not the value 1 

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

4. zeros, ones, empty 
   - zeros
       - creates an array filled with zeros
       - specify the shape of the array using tuple or single integer as argument
   - ones
       - creates an array filled with ones
   - empty 
       - creates an array without initializing its values

In [14]:
np.zeros(5)  

# generates array of 5 zeros 

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 3))

# generates a 3 x 3 matrix filled with zeros 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3, 3), dtype=int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones(5)

# generates array of 5 ones 

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

5. identity and eye
   - identity 
       - creates a square identity matrix of size n x n, n should be supplied argument 
   - eye
       - creates an identity matrix with ones on a specified diagonal (main diagonal by default) and zeros elsewhere. - The arguments are as follows:
           - Number of rows
           - (Optional) Number of columns. If not specified, M is set to N.
           - (Optional) Index of the diagonal to fill with ones. The main diagonal has an index of 0 (default).


In [22]:
np.identity(3) 

# generates a 3 x 3 matrix with 1's diagonal (from top left) , identity theorem 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3, 3)

# allows you to specify the number of rows and columns for the identity matrix
# 1's diagonal (from top left) , identity theorem 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(8, 4)

# generates a 8 x 4 matrix with 1's diagonal (from top left) , identity theorem 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.eye(8, 4, k=1)

# 8 x 4 matrix, ones are placed on the first diagonal above the main diagonal (with an index of k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.eye(8, 4, k=-3)

# 8 x 4 matrix, ones are placed on the diagonal three positions below the main diagonal (with k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [27]:
"Hello World"[6]


# character at index 6 is the letter 'W'


'W'